"""add column vk_id to  user table

Revision ID: 5bef7eeb1d62
Revises: bacfcc16b24f
Create Date: 2025-08-20 19:13:45.821653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bef7eeb1d62'
down_revision: Union[str, Sequence[str], None] = 'bacfcc16b24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vk_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'users', ['vk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'vk_id')
    # ### end Alembic commands ###
